spring:
  application:
    name: academic-service

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: never